url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ministério Família"
lang: 'pt-br'
cnpj: "40.812.932/0001-53"
whatsapp: "98317-9545"
description: "Projeto do Coração de Deus"
enderecos:
  - logradouro: "Rua Padre Pedro Pinto"
    numero: 4938
    bairro: "Venda Nova"
    cidade: "Belo Horizonte"
    uf: "MG"

redes_sociais:
  - icon: "facebook-official"
    url: "https://www.facebook.com/ministeriofamiliapcd"
    nome: "Facebook"
  - icon: "instagram"
    url: "https://www.instagram.com/_ministeriofamilia"
    nome: "Instagram"

  
google_api_key: AIzaSyBOdEQYo2LW1pnOjjcOO0nAHBEOnuMDFIA


banco:
  nome: 'Bradesco'
  agencia: 464
  cc: '64.707-1'

cultos:
  - dia: 'Quartas-feiras'
    nome: 'Quarta das Maravilhas de Deus'
    horarios: '08:00, 15:00 e às 19:00'
    imagem: '/assets/img/mar-vermelho.png'
  - dia: 'Sexta-Feira'
    nome: 'Sexta do Favor de Deus'
    horarios: '08:00, 15:00 e às 19:00'
    imagem: '/assets/img/cruz.jpg'
  - dia: 'Domingos'
    nome: 'Culto da Família'
    horarios: '09:00, 15:00 e às 19:00'
    imagem: '/assets/img/familia.jpg'


pastores:
  - nome: 'Reinaldo Rosário'
    bio: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque sequi illum excepturi, fugit nemo tempora tempore mollitia sapiente laboriosam a voluptate dolorum nobis at consectetur corporis qui modi maiores assumenda facilis reprehenderit sint quaerat. Excepturi sed est modi corrupti, consequatur quibusdam quasi aut nihil ullam, fuga perferendis hic deserunt illo et similique mollitia optio, commodi necessitatibus recusandae! Consequatur, animi. Quae odit alias quod perspiciatis dolore saepe totam similique, dicta corrupti. Nesciunt enim itaque consequuntur magni atque. Praesentium natus eligendi ipsum adipisci quas cupiditate cumque officiis! Perspiciatis at reiciendis ad tempore quia! Laudantium odit doloribus eos aliquam earum dolorum fugiat. Voluptatibus?'
    imagem: 'reinaldo-rosario.jpg'
  - nome: 'Dimas Raphael'
    bio: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque sequi illum excepturi, fugit nemo tempora tempore mollitia sapiente laboriosam a voluptate dolorum nobis at consectetur corporis qui modi maiores assumenda facilis reprehenderit sint quaerat. Excepturi sed est modi corrupti, consequatur quibusdam quasi aut nihil ullam, fuga perferendis hic deserunt illo et similique mollitia optio, commodi necessitatibus recusandae! Consequatur, animi. Quae odit alias quod perspiciatis dolore saepe totam similique, dicta corrupti. Nesciunt enim itaque consequuntur magni atque. Praesentium natus eligendi ipsum adipisci quas cupiditate cumque officiis! Perspiciatis at reiciendis ad tempore quia!'
    imagem: 'dimas-raphael.jpg'
  - nome: 'Victor Hugo'
    bio: 'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eaque sequi illum excepturi, fugit nemo tempora tempore mollitia sapiente laboriosam a voluptate dolorum nobis at consectetur corporis qui modi maiores assumenda facilis reprehenderit sint quaerat. Excepturi sed est modi corrupti, consequatur quibusdam quasi aut nihil ullam, fuga perferendis hic deserunt illo et similique mollitia optio, commodi necessitatibus recusandae! Consequatur, animi. Quae odit alias quod perspiciatis dolore saepe totam similique, dicta corrupti. Nesciunt enim itaque consequuntur magni atque. Praesentium natus eligendi ipsum adipisci quas cupiditate cumque officiis! Perspiciatis at reiciendis ad tempore quia!'
    imagem: 'dimas-raphael.jpg'
