url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ministério Família"
lang: 'pt-br'
cnpj: "99.999.999.99/0001-99"
whatsapp: "98317-9545"
description: "Projeto do Coração de Deus"
enderecos:
  - logradouro: "Rua Padre Pedro Pinto"
    numero: 4935
    bairro: "Venda Nova"
    cidade: "Belo Horizonte"
    uf: "MG"

redes_sociais:
  - icon: "facebook-official"
    url: "teste"
    nome: "Facebook"
  - icon: "instagram"
    url: "https://www.instagram.com/_ministeriofamilia"
    nome: "Instagram"

  
google_api_key: AIzaSyBOdEQYo2LW1pnOjjcOO0nAHBEOnuMDFIA


cultos:
  - dia: 'Quartas-feiras'
    nome: 'Quarta das Maravilhas de Deus'
    horarios: '08:15 e às 19:00'
    imagem: '/assets/img/mar-vermelho.png'
  - dia: 'Sexta-Feira'
    nome: 'Sexta do Favor de Deus'
    horarios: '08:15 e às 19:00'
    imagem: '/assets/img/cruz.jpg'
  - dia: 'Domingos'
    nome: 'Culto da Família'
    horarios: '09:00, 15:00 e às 19:00'
    imagem: '/assets/img/familia.jpg'