url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Ministério da Família" # the name of your site, e.g. ACME Corp.
lang: 'pt-br'
cnpj: "99.999.999.99/0001-99"
